### ISSUE TITLE
Can we take a full-screen (height) screenshot?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-nightwatch#11]
Can we get a screenshot that includes "_below the fold_" ?

**Comment by nelsonic** [comment]
In fairness though, this is not the behaviour that the "_end user_" will see, so we should probably, _scroll_ and _then_ take our required screenshot...?

**Comment by nelsonic** [comment]
Apparently, full-screen screenshots are the _default_ in Internet explorer:
![windows10 internetexplorer 11 0 github_00_dwyl](https://cloud.githubusercontent.com/assets/194400/16459478/d042355e-3e1a-11e6-87e5-a0528eebe7ed.png)

**Comment by honglish** [comment]
Is there a way to disable this effect in IE to make the screenshots consistent?

**Comment by nelsonic** [comment]
@honglish _good_ question, I don't know.
perhaps a question for: https://github.com/nightwatchjs/nightwatch/issues ?
