### ISSUE TITLE
Cold selenium-download fails

### ISSUE THREAD

**Issue by justinmc** [dwyl/learn-nightwatch#28]
Running the [basic nightwatch config](https://github.com/dwyl/learn-nightwatch/blob/master/nightwatch.conf.BASIC.js) on a fresh install, where the selenium jar doesn't yet exist, fails with "Error: Unable to access jarfile ./node_modules/nightwatch/bin/selenium.jar".

I believe it attempts to start downloading the selenium jar, but nightwatch looks for it and kills its process before it can finish.  Adding the selenium jar manually fixes it, but that kind of defeats the purpose of using selenium-download.

Am I doing something wrong here or does this really not work?

**Comment by LasaleFamine** [comment]
Did you run `node nightwatch.conf.BASIC.js` before running nightwatch itself?
You need to run the function inside the configuration file that will download the `selenium.jar` for you.

If you take a look to the `package.json` within the root of the repository, you will find a line within the `scripts` section:
``` js
...
"scripts":  {
    "postinstall": "node nightwatch.conf.js",
...
```
Basically when you run  `npm install` in a fresh copy of this repository, this line will be executed at the end of the `npm install` process, running the function inside the config file that will download selenium.

I hope it helps!

**Comment by justinmc** [comment]
@LasaleFamine That's exactly what I was missing, thank you!

**Comment by nelsonic** [comment]
@justinmc apologies if that was _unclear_ thanks for learning with us! ⭐
