### ISSUE TITLE
Not using env files

### ISSUE THREAD

**Issue by jinky32** [dwyl/learn-nightwatch#29]
Hi,

I used the quick version of the tutorial - cloning the repo locally etc.  However when I try and run my tests I get an error:
`WARNING: env2 was required to load an .env file: learn-nightwatch/.env NOT FOUND!`

If I comment out the `require('env2')('.env')` at the top of the nightwatch.conf.js I still get an `npm ERR!` although it no longer mentions the missing file. However after i run the `npm test` command I can see that it's running `nightwatch --env local`.

How do I resolve this?

**Comment by nelsonic** [comment]
@jinky32 thanks _very much_ for reporting this issue (_and helping us to improve our tutorial_)!

First, can you give us a bit more info about your system: what Operating System are you using?

**Comment by nelsonic** [comment]
I _just_ tried the steps in the Quick-start:
```sh
git clone https://github.com/dwyl/learn-nightwatch.git 
cd learn-nightwatch
npm install
npm test
```
and get:
![learn-nightwatch-quickstart](https://cloud.githubusercontent.com/assets/194400/18452519/0e5ec2d2-7933-11e6-912d-11e2b15638cb.png)

I'm running on a Mac but the experience should be the same on Linux/Windows...

@jinky32 if you can give as a bit more insight or even upload a screenshot we'd love to help you make progress! 👍

**Comment by jinky32** [comment]
@nelsonic thanks for the quick reply. I'm running Ubuntu 16.  The below is what I get out of the box
<img width="735" alt="screen shot 2016-09-13 at 8 54 22 am" src="https://cloud.githubusercontent.com/assets/932188/18465738/345177c0-7990-11e6-897e-38f2327b300b.png">

If I modify package.json from ` "test": "./node_modules/.bin/nightwatch --env local",` to  "test": "./node_modules/.bin/nightwatch,` and run I get 
<img width="725" alt="screen shot 2016-09-13 at 8 55 39 am" src="https://cloud.githubusercontent.com/assets/932188/18465763/528bf288-7990-11e6-9997-8777c3a1bd5e.png">

However if (with the modified package.json) I run `node_modules/.bin/nightwatch` rather than `npm test` then all good
<img width="733" alt="screen shot 2016-09-13 at 8 56 28 am" src="https://cloud.githubusercontent.com/assets/932188/18465790/872663b6-7990-11e6-824b-11acaf43caab.png">

**Comment by jinky32** [comment]
Hmm, actually I say all good, but I can't make the test fail.  For example if i modify the github test to look for some other copy in the body no failure is reported

**Comment by nelsonic** [comment]
@jinky32 this is _very_ strange. 😕 
We don't see a `child process for coverageChecker` on ours. what is that?
Has anything _changed_ in your `nightwatch.conf.js` or either of `/test/e2e/guineaPig.js` or `/test/e2e/github.js` that requires starting such a child process?

**Comment by cepm-nate** [comment]
I downloaded the git repo as a zip, extracted to "A:\vpubweb\testing", then ran the following commands in a terminal:
`npm install`
`npm test`
And this is the result of the "npm test" command:
![image](https://cloud.githubusercontent.com/assets/10284464/18492007/039a1032-79be-11e6-86e0-43d545226c5f.png)
What's up with the env errors? This is on windows 10 x64.

**Comment by nelsonic** [comment]
@cepm-nate Yeah, let's add a note in the Readme! 👍

**Comment by gaddamsridhar6** [comment]
How Do we Configure Different environments in VSTS for Running the Smoke tests in Dev env and Regression in QA env
