### ISSUE TITLE
Step-by-Step tutorial is missing a couple steps

### ISSUE THREAD

**Issue by cepm-nate** [dwyl/learn-nightwatch#30]
It's a little unclear what we should do in our own project to get it setup. Perhaps this is assumed by veterans of nightwatch, but I think it'd be great to spell it out in the readme.

Following the install of both selenium-download and nightwatch (via the steps mentioned):

- Where do I put the nightwatch.conf.BASIC.js file? (Answer: within the same directory you ran the previous commands. You could start by copying it from node_modules\selenium-download.)
- Run `node nightwatch.conf.BASIC.js` to download selenium for the first time.

Perhaps something along these lines could be added to the main readme?

**Comment by nelsonic** [comment]
@cepm-nate _thanks_ for your _feedback_ and for opening this _discussion_! 👍 
Are you referring to the "_Quick Start_" or the "[_Step-by-Step Tutorial_](https://github.com/dwyl/learn-nightwatch#step-by-step-tutorial)"?

We have a [`postinstall` script](https://github.com/dwyl/learn-nightwatch/blob/a7cf04329736ec87471d83cc31699eeb73bb77e0/package.json#L10) in the `package.json` which is meant to handle installing selenium once the `node_modules` are installed, did that _work_ on Windows...?

The `nightwatch.conf.BASIC.js` is there as an example of how "_basic_" the config file _can_ be.

The _actual_ Nightwatch tests in the example are run using `nightwatch.conf.js` ...
our sincere apologies if there is any confusion in this. 

If you have time, please send us a Pull Request with your suggestions for improvement. Thanks!

**Comment by cepm-nate** [comment]
For the "Step by Step" section, the "your own project" section.

Do you assume that people will download this LEARNING stuff into their own project?

**Comment by nelsonic** [comment]
@cepm-nate ah... ok. So maybe we need a section with some advice on using Nightwatch for a cordova/phonegap project...?

**Comment by cepm-nate** [comment]
Not so much for using it on a Corodova/phonegap project (although mentioning that on the page may help search engines), but perhaps a section about "Additional steps when using it to test a non-NPM project"? The framework works great for testing any websites, even non-javascript ones!

**Comment by nelsonic** [comment]
@cepm-nate good plan.

**Comment by cepm-nate** [comment]
pull request created.

**Comment by nelsonic** [comment]
@cepm-nate thanks! PR Merged! 👍 
please close off the issue if you are happy... ✅

**Comment by cepm-nate** [comment]
Thanks!

**Comment by jpfernandezl** [comment]
postinstall does not download the jar file into the bin folder on windows 8

**Comment by nelsonic** [comment]
@jpfernandezl did you see my comment: https://github.com/dwyl/learn-nightwatch/issues/34#issuecomment-265841163 ?
(_have you managed to open an issue on_ https://github.com/groupon/selenium-download/issues ?)
