### ISSUE TITLE
Would it be beneficial for me to add a short section to the readme on using sauce connect? 

### ISSUE THREAD

**Issue by Conorc1000** [dwyl/learn-nightwatch#36]
For my project I have found it very useful to set up sauce [connect,](https://wiki.saucelabs.com/display/DOCS/Setting+Up+Sauce+Connect) which allows me to serve the app on my local host and give sauce labs access to the app to run the tests.

**Comment by Conorc1000** [comment]
There are many ways to set up sauce connect, i found the simplest to be [Sauce Connect Launcher](https://wiki.saucelabs.com/display/DOCS/Using+Sauce+Connect+Launcher).

**Comment by nelsonic** [comment]
@Conorc1000 _yes_, please! go for it! 👍

**Comment by Conorc1000** [comment]
This has been added in PR #38

**Comment by nelsonic** [comment]
Thanks again @Conorc1000 🎉
