### ISSUE TITLE
Test.only equivalent for nightwatch

### ISSUE THREAD

**Issue by naazy** [dwyl/learn-nightwatch#42]
I think it would be useful to add some info about running single tests on nightwatch. Linked to https://github.com/OxfordAbstracts/application/issues/2106

**Comment by nelsonic** [comment]
@naazy there _appears_ to be an "_accepted_" way of doing this using the `--testcase` flag: http://stackoverflow.com/questions/28308990/how-to-run-a-single-test-in-nightwatch 

What are the pros/cons of using `--testcase` vs. `--tag` ....? (_thanks for investigating this!_)

**Comment by naazy** [comment]
Hmm I couldn't figure out what name we would have to use with --testcase so went for --tag instead. You can also give tests multiple tags and give the same tags to mulitple tests so you could run all tests with the tag 'word-count' if you wanted which I think could be really useful http://nightwatchjs.org/guide#test-tags

**Comment by nelsonic** [comment]
@naazy sounds good. thanks for _clarifying_. 👍
