### ISSUE TITLE
Doesn't work on arch

### ISSUE THREAD

**Issue by qacwnfq** [dwyl/learn-nightwatch#51]
Following your guide doesn't work on Arch Linux.
Neither the repo nor the setup work.
I've played with the configs but it seems to be a selenium thing,
since the connection is always refused. I can start the selenium server manually though.

**Comment by ryanpcmcquen** [comment]
Is there any error output?

**Comment by qacwnfq** [comment]
Not really,

[user@home learn-nightwatch]$ npm test

> learn-nightwatch@1.0.23 test /home/user/repos/learn-nightwatch
> nightwatch --env local

Starting selenium server in parallel mode... started - PID:  16643

Started child process for: e2e/github 
Started child process for: e2e/guineaPig 
Started child process for: e2e/upload_screenshots_to_s3 
 e2e/upload_screenshots_to_s3   If you want to upload Screenshots to S3
      please set your AWS Environment Variables (see readme).
 e2e/upload_screenshots_to_s3   \n
 e2e/upload_screenshots_to_s3   [Upload Screenshots To S3] Test Suite
=========================================

  >> e2e/upload_screenshots_to_s3 finished.  


  >> e2e/guineaPig finished.  


  >> e2e/github finished.  


npm ERR! Test failed.  See above for more details.

**Comment by ryanpcmcquen** [comment]
You can wrap the output in 3 backticks:
\`\`\`
OUTPUT
\`\`\`

And it will show up as formatted code. Just for reference, what version of `node` and `npm` do you have?

**Comment by qacwnfq** [comment]
Thanks
```
[user@home learn-nightwatch]$ node --version
v6.9.1
[user@home learn-nightwatch]$ npm --version
3.10.9

```

**Comment by ryanpcmcquen** [comment]
So you've run this?

```
git clone https://github.com/dwyl/learn-nightwatch.git && cd learn-nightwatch && cp sample.env .env
npm install
npm test
```

**Comment by qacwnfq** [comment]
yes. The strange thing is it worked on debian before but it just won't on my arch system.

**Comment by LasaleFamine** [comment]
Did you try without the `parallel` mode? Seems like `npm` kills itself during the process. And also, do you have the same hardware configuration in both systems?

**Comment by qacwnfq** [comment]
running 
```
npm test --verbose
```
leads to a line
```
npm info lifecycle learn-nightwatch@1.0.23~test: Failed to exec test script
npm ERR! Test failed.  See above for more details.
```

If I specify the confing nightwatch.conf.js or nightwatch.conf.BASIC.js I get
```
> nightwatch "nightwatch.conf.BASIC.js"

Starting selenium server... started - PID:  27647

[src_folders] Test Suite
============================

npm verb lifecycle learn-nightwatch@1.0.23~test: unsafe-perm in lifecycle true
npm verb lifecycle learn-nightwatch@1.0.23~test: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/fredrik/repos/learn-nightwatch/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
npm verb lifecycle learn-nightwatch@1.0.23~test: CWD: /home/fredrik/repos/learn-nightwatch
npm info lifecycle learn-nightwatch@1.0.23~posttest: learn-nightwatch@1.0.23
npm verb exit [ 0, true ]
npm info ok 
```

So it seems there is a problem with the config/finding the test scripts.

**Comment by ryanpcmcquen** [comment]
Works here on Slackware. Have you tried?

```
git clean -xdf
cp sample.env .env
npm install
npm test
```

**Comment by qacwnfq** [comment]
Didn't fix it but I checked the debian system again. I was using npm 2.15.1.
Maybe learn-nightwatch doesn't work correctly with npm3 yet, considering the changes?

I post an update as soon as I get home.
