### ISSUE TITLE
Need help with - new clone of learn-nightwatch testing (npm ERR!) 

### ISSUE THREAD

**Issue by mushibugyo** [dwyl/learn-nightwatch#56]
Hello Everyone,
I was hoping to get some assistance. I am testing out nightwatch.js for the first time. I have created a new CentOS VM and installed all of the required components (node.js, java, etc). I then cloned the github learn-nightwatch repository and everything seems to have gone smoothly. However, after running "node nightwatch.conf.BASIC.js in order to download the selenium.jar file I run into an issue when I actually run the tests: npm test.

The attached snip contains the error:

![npmerr](https://cloud.githubusercontent.com/assets/26121085/23472984/a1159334-fe7c-11e6-8bd1-87acd07c3d30.PNG)

Additional information:

npm version = 4.1.2
node version = 7.6.0

Also, here's a snip using npm test --verbose

![npmverbose1](https://cloud.githubusercontent.com/assets/26121085/23473998/3dd8c0d0-fe80-11e6-9f7d-da1d133676b0.PNG)
![npmverbose2](https://cloud.githubusercontent.com/assets/26121085/23473999/4028347e-fe80-11e6-8eca-bae7a9444590.PNG)

Any help with this matter is greatly appreciated!!

Cheers
MB

**Comment by naazy** [comment]
Hi @mushibugyo What's the first line of your guineaPig.js?

**Comment by mushibugyo** [comment]
Heya @naazy here is a snip of the file itself:

![guineapigcontents](https://cloud.githubusercontent.com/assets/26121085/23474088/8922d7b0-fe80-11e6-846e-36d301b04394.PNG)

Cheers
MB

**Comment by naazy** [comment]
Please could you try changing the first line to
```var config = require('../../nightwatch.conf.BASIC.js');```

and try running the command again?

Thanks

**Comment by mushibugyo** [comment]
@naazy ... Similar error as before. Please see snips:

![npmverbose1a](https://cloud.githubusercontent.com/assets/26121085/23474909/7b11edde-fe83-11e6-88a6-556bdd3319ef.PNG)
![npmverbose2a](https://cloud.githubusercontent.com/assets/26121085/23474912/7d63b2ac-fe83-11e6-9c44-c60bf768fd9e.PNG)

Cheers
MB

**Comment by mushibugyo** [comment]
Seems like there's another thread with a similar problem to my own: [Issue 51](https://github.com/dwyl/learn-nightwatch/issues/51).

**Comment by naazy** [comment]
@mushibugyo I've just tried cloning myself and running npm t and I get:

<img width="560" alt="screen shot 2017-03-01 at 20 16 30" src="https://cloud.githubusercontent.com/assets/11833296/23479337/0bd42cb4-febc-11e6-952f-1f78fca6f2a4.png">

Have you literally just cloned? Or have any of the files been changed at all? Also your browser is Chrome right?

**Comment by mushibugyo** [comment]
@naazy  It's a straight up clone. I also checked and after running the nightwatch.conf.BASIC.js there required selenium server as well as the chromedriver are both downloaded.

**Comment by naazy** [comment]
@mushibugyo OS x el capitan

**Comment by mushibugyo** [comment]
In order to duplicate my issue exactly try spinning up a VM with CentOS and then try a full clone again. Let me know what happens.

Cheers
MB

**Comment by mushibugyo** [comment]
I had a chance to spin up an Ubuntu (16.04) and managed to get everything up and running. See snip below:
![successubuntu](https://cloud.githubusercontent.com/assets/26121085/23490553/441417dc-fec7-11e6-8e9a-66565237b5b1.PNG)

However, before this was up and functioning properly I used this [script](https://gist.github.com/ziadoz/3e8ab7e944d02fe872c3454d17af31a5) to install chrome webdriver + selenium server. Afterwards everything worked like a charm.

Cheers
MB

**Comment by naazy** [comment]
Great news @mushibugyo! Please close this issue if you are satisfied that it's been resolved 😄

**Comment by mushibugyo** [comment]
I managed to get nightwatch up and running on CentOS by installing Gnome Desktop and running it from terminal via desktop.

**Comment by suwarna-wade** [comment]
@mushibugyo Hi I am getting same error as you had. But I want to run tests without UI. How can I do it?

**Comment by defdata** [comment]
I have this same problem on windows. It only happens if i try to require something outside of module.exports, otherwise everything works fine.
