### ISSUE TITLE
demo test failed

### ISSUE THREAD

**Issue by 1syazwan** [dwyl/learn-nightwatch#58]
Results for:  Demo test GitHub
 √ Element <body> was visible after 67 milliseconds.
 × Testing if element <body> contains text: "do what you love".  - expected "do what you love" but got: "Skip to content

**Comment by nelsonic** [comment]
@1syazwan thanks for reporting this. _someone_ removed the "slogan" from our GitHub org page ...

**Comment by 1syazwan** [comment]
Please get me notified once you had it fixed :)

**Comment by emersonmellado** [comment]
fix suggestion as [PR](https://github.com/dwyl/learn-nightwatch/pull/61)

**Comment by emersonmellado** [comment]
@1syazwan can you check it again?

**Comment by emersonmellado** [comment]
We are good on this one, Just confirmed :)

**Comment by syazwanhazim** [comment]
thanks for this clarification
