### ISSUE TITLE
Timed out while waiting for element <body> on quick start (5mins)

### ISSUE THREAD

**Issue by zangarmarsh** [dwyl/learn-nightwatch#63]
I'm trying nighwatch for the first time, following your quick start guide step by step and that's what I got from npm test:
![schermata da 2017-07-05 08-39-29](https://user-images.githubusercontent.com/13025377/27853939-1bb84136-6165-11e7-9e91-11e392153059.png)

**Comment by nelsonic** [comment]
@zangarmarsh hmm... is your code on GitHub? (_can you push it up so we can help debug_?)
