### ISSUE TITLE
the step by step guide can be improved

### ISSUE THREAD

**Issue by jaysoifer** [dwyl/learn-nightwatch#66]
I noticed it took me a few minutes to figure out (by going to the original folder) how to properly name the `guinePig.js` in the `test/e2e` folder in section "Installation (in details)" part "8) Create Your Nightwatch Test".

**Comment by nelsonic** [comment]
@jaysoifer thanks for opening this issue 🎉 
and _apologies_ that the instructions weren't clear. 😞
