### ISSUE TITLE
Selenium / Chrome driver download enhancement

### ISSUE THREAD

**Issue by gsouquet** [dwyl/learn-nightwatch#76]
Hi,

I believe I found a better way to get both selenium and webdrivers.

* https://www.npmjs.com/package/selenium-server
* https://www.npmjs.com/package/chromedriver

Those two packages bring the binaries and expose a path to it. We end up with a nightwatch config looking like the following: 

```js
const seleniumServer = require("selenium-server");
const chromedriver = require("chromedriver");

module.exports = {
  // ...
  selenium: {
    "server_path" : seleniumServer.path,
    "cli_args" : {
      "webdriver.chrome.driver" : chromedriver.path
    }
  },
  // ...
};
```

I believe this simplifies the installation process. I'm willing to open a PR to do the changes. Just wanted to run that by you first

**Comment by nelsonic** [comment]
@gsouquet great find and _thank you_ for opening this issue to inform/discuss!
Yes, _please_ do open a PR with this proposed change. thanks! 👍

**Comment by dale-c-anderson** [comment]
Running `node nightwatch.conf.BASIC.js` with this configuration did not install chromedriver for me. Instead, I got this:
```
$ node nightwatch.conf.BASIC.js 
module.js:538
    throw err;
    ^

Error: Cannot find module 'chromedriver'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/danderson/repos/git.acromedia.com/telus/evs/nightwatch.conf.BASIC.js:3:22)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
```
I had to manually `npm install chromedriver` to proceed.

```
npm install selenium-server --save-dev

I'm using node v8.9.3 and npm v5.5.1 on Ubuntu 16.04.

**Comment by nelsonic** [comment]
@gsouquet given that your PR has been merged I'm closing this issue.
feel free to re-open if you feel it has not been addressed. 👍
