### ISSUE TITLE
Can we run the e2e tests on TravisCI (or other CI)?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-nightwatch#8]
Given that we have the selenium start/shutdown and test run in a single command `npm run e2e`,
we could _try_ to run this on Travis...

**Comment by nelsonic** [comment]
Sadly this did not work looks like the Selenium server did not start: https://travis-ci.org/nelsonic/learn-nightwatch/builds/137542228#L185
we don't have an easy way of _debugging_ it...
But I'm going to try and install `Java` before running the tests... 
http://superuser.com/questions/993718/can-i-install-java-8-on-travis-ci-for-a-python-project

**Comment by nelsonic** [comment]
No luck ... https://travis-ci.org/nelsonic/learn-nightwatch/builds/137544553#L326 😢

**Comment by nelsonic** [comment]
Looks like Travis-CI is not going to be an option... see: https://github.com/travis-ci/travis-ci/issues/4090 (_for now_...)

**Comment by nelsonic** [comment]
Hold on, found this: http://stackoverflow.com/questions/18456611/is-it-possible-to-set-up-travis-to-run-tests-for-several-languages which leads to http://entulho.fiatjaf.alhur.es/guias/how-to-use-node-along-with-other-language-on-travis-ci/ which suggests that we set the language in `.travis.yml` to Java and then run the tests in a script ... e.g:
```yml
language: java

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
  
script:
  - npm test
```
This example is for `Go` but still relevant: https://github.com/OrangeTux/Goppetto/blob/develop/.travis.yml

**Comment by nelsonic** [comment]
Setting the language to Java did not work ... https://travis-ci.org/nelsonic/learn-nightwatch#L417

attempting: http://superuser.com/questions/993718/can-i-install-java-8-on-travis-ci-for-a-python-project#comment1405598_993718

**Comment by nelsonic** [comment]
Note: This works on CodeShip without *any issues*:
![learn-nightwatch-codeship-passes](https://cloud.githubusercontent.com/assets/194400/16052035/30c4a6ae-325a-11e6-8be7-f6338da4be7c.png)
![learn-nightwatch-codeship-2](https://cloud.githubusercontent.com/assets/194400/16052037/34c92342-325a-11e6-8b32-d5d22cf68e42.png)

**Comment by nelsonic** [comment]
Travis is _pure frustration_ ... 😞 
https://travis-ci.org/nelsonic/learn-nightwatch/builds/137568733#L138

**Comment by nelsonic** [comment]
Attempt to run the selenium jar file as a background process: 
http://stackoverflow.com/questions/12102270/run-java-jar-file-on-a-server-as-background-process

**Comment by nelsonic** [comment]
Attempt to use https://github.com/angular/webdriver-manager to run selenium...

**Comment by nelsonic** [comment]
LoL: https://travis-ci.org/nelsonic/learn-nightwatch/builds/137772914#L230

**Comment by nelsonic** [comment]
Check status of selenium server before running the tests: http://localhost:4444/wd/hub/status
![selenium-status](https://cloud.githubusercontent.com/assets/194400/16086389/41ef264e-3317-11e6-908d-a523ceac034f.png)

from: http://stackoverflow.com/questions/6517501/selenium-2-how-to-check-that-server-is-running-and-stop-the-server

**Comment by nelsonic** [comment]
Selenium is Running! https://travis-ci.org/nelsonic/learn-nightwatch/builds/137849262
![travis-loads-selenium](https://cloud.githubusercontent.com/assets/194400/16088410/e0263daa-331e-11e6-8bf3-f14f9fe4915f.png)

But I cannot access it!
![travis-cannot-connect-to-selenium](https://cloud.githubusercontent.com/assets/194400/16088423/f098fa1a-331e-11e6-82e2-497b03a6d486.png)

**Comment by nelsonic** [comment]
When we attempt to start selenium in `nightwatch.json` we get: https://travis-ci.org/nelsonic/learn-nightwatch/builds/137876826#L192
![travis-fails-when-nightwatch json-set-to-start-selenium](https://cloud.githubusercontent.com/assets/194400/16092078/3f945754-332e-11e6-8ac1-3e1315a1cc1d.png)

**Comment by nelsonic** [comment]
Trying the advice in: https://github.com/travis-ci/travis-ci/issues/2843 to `sleep ...` before running the tests!

**Comment by nelsonic** [comment]
Ok, I'm shelving this for now. Its taken *way* too much time to do something that should be _simple_...!!
These guys _appear_ to have it working: https://github.com/Khan/KaTeX/blob/master/.travis.yml
which lead me to: https://github.com/SeleniumHQ/docker-selenium

But I don't have _time_ to investigate this further today... if anyone else has time to try and debug this, please go for it! $100 bounty for successfully running Selenium (Nightwatch) tests on Travis-CI. 💲

**Comment by nelsonic** [comment]
Sadly, Travis-CI is _still_ not cooperating:
https://travis-ci.org/nelsonic/learn-nightwatch/builds/140380579#L205

Appears we nee to use [`Xvfb`](https://en.wikipedia.org/wiki/Xvfb) see: http://stackoverflow.com/a/23673054/1148249

See instructions on Travis-CI:
https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI

**Comment by nelsonic** [comment]
Adding `Xvfb` as instructed by Travis-CI did not work. https://travis-ci.org/nelsonic/learn-nightwatch/builds/140396366
<img width="887" alt="travis-learn-nightwatch-fail" src="https://cloud.githubusercontent.com/assets/194400/16364467/5f2caa6c-3bdf-11e6-8735-1dd6cd5b8c18.png">

**Comment by nelsonic** [comment]
I _really_ don't have time to mess about with Travis-CI anymore ... 
if anyone wants to pitch in and figure this out I have £100 with your name on it.
(_preferably with the ability to take/save screenshots..._)

This _was_ the state _before_ I gave up: my `.travis.yml` file:
```sh
language: node_js
node_js:
  - 4.4.6
before_install:
  - java -version
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
```
Outcome:
<img width="1031" alt="learn-nightwatch-travis-ci-fail-1of2" src="https://cloud.githubusercontent.com/assets/194400/16364599/281075d2-3be3-11e6-9770-fb6a9fdc8b1e.png">
<img width="1031" alt="learn-nightwatch-travis-ci-fail-2of2" src="https://cloud.githubusercontent.com/assets/194400/16364600/2c175e3e-3be3-11e6-99cb-3cd00dd91358.png">

@des-des / @jrans you gents _appear_ to have some practice/experience of using Nightwatch in `cmt-integration` ... if you have time to look at this, just invoice me for how ever long it takes you to get it working! 😉

**Comment by amilajack** [comment]
@nelsonic would a PR for this still be welcome? Think I might give it a go.

**Comment by amilajack** [comment]
I'm getting the error:
```
TypeError: Path must be a string. Received { url: 'http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.0.jar'
```

Seems like `env2` isn't configured properly in the config.

**Comment by nelsonic** [comment]
@amilajack I think this error relates to the using the latest version of `download` not working with `node` v6.x see: https://github.com/dwyl/learn-nightwatch/issues/24 
we _first_ need make `selenium-download` compatible with node v6.x ... I forked the repo: https://github.com/dwyl/selenium-download and started to debug why it wasn't working ... (_you are a contributor if you want to take a look_)

**Comment by NickStefan** [comment]
thank god! now I know i'm not crazy. Ive been trying to get our own nightwatch running on travis CI for days, and simple things are just not working. Selenium runs on a clean travis build, but always has an empty body tag. When I ssh into the travis build under debug mode, I cant get selenium to even load. (why should it be any different from non debug!?)

The only person I've seen who actually appears to have it working on travis is: https://github.com/zeroasterisk/meteor-travis-ci-nightwatch/blob/master/nightwatch.json

but even after copying them, no luck :(.

Looks like we'll be breaking up with travis...

**Comment by nelsonic** [comment]
@Danwhy & @SimonLab what are you doing _differently_ to run your Nightwatch tests on Travis-CI ?
They appear to run without issues: https://travis-ci.org/TheScienceMuseum/collectionsonline/builds/169499325#L1957
`CC`: @Conorc1000

**Comment by Danwhy** [comment]
It could be because we're running ours through saucelabs

**Comment by nelsonic** [comment]
@Danwhy next time we're in the same room please walk me through it so I _understand_. thanks! 😉

**Comment by justinmc** [comment]
For whatever it's worth, I seem to have gotten my project to work with Nightwatch tests on Travis using this guide, but I had to settle with only using phantomjs: https://github.com/Autodesk/molecule-2d-for-react/pull/15

**Comment by nelsonic** [comment]
@justinmc nice work! thanks for confirming you got it working with PhantomJS! 👍

**Comment by nelsonic** [comment]
@jackcarlisle this is how I log progress in a "Spike"... it lets someone else see what has been _attempted_ and can pick up the baton...

**Comment by jackcarlisle** [comment]
@nelsonic 👍 I'll do the same for the karma spike

**Comment by gregorybesson** [comment]
Hello guys,

I've been able to make it work with Chrome in Travis: https://github.com/AdFabConnect/abejs/blob/master/.travis.yml

1. You have to use the beta build from travis
```
sudo: required
dist: trusty
```

2. You launch xvfb + install the last stable version of Chrome
```
before_install:
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sudo apt-get update
 - sudo apt-get install -y libappindicator1 fonts-liberation
 - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
 - sudo dpkg -i google-chrome*.deb
```

3. last but not least, switch to the last version of jdk:
``` 
script:
  - jdk_switcher use oraclejdk8
```

The nightwatch config file is here:https://github.com/AdFabConnect/abejs/blob/master/nightwatch.conf.js

Hope it will work for you ;)

**Comment by Conorc1000** [comment]
Since this issue was made this short piece has been added to the readme.
"Running your Nightwatch tests on CircleCi."

**Comment by qacwnfq** [comment]
@gregorybesson
Thanks, it works!
For me the deciding part seems to have been export DISPLAY and starting xvfb.

**Comment by gregorybesson** [comment]
@qacwnfq U welcome. Indeed, we must start xvfb for chrome to be able to launch

**Comment by ritz078** [comment]
@nelsonic Tests running on Travis with saucelabs
<img width="1200" alt="screen shot 2017-03-15 at 1 27 23 am" src="https://cloud.githubusercontent.com/assets/5389035/23919902/a94f09a2-091e-11e7-9472-b99c2f771624.png">

Here is the code https://github.com/ritz078/embed.js/pull/228

**Comment by nelsonic** [comment]
@ritz078 nice one. 👍 
If you have time to send us a Pull Request explaining the steps to get it setup using sauce connect, it would be _massively_ appreciated! ❤️

**Comment by ritz078** [comment]
I will create a PR.

**Comment by nelsonic** [comment]
@ritz078 thank you for your _fantastic_ contribution! 👍 
I have reviewed & merged your Pull Request. ✅ 
Please email me to claim your reward! 🥇

**Comment by QuantumInformation** [comment]
Will this thread help me here: https://stackoverflow.com/questions/47577859/running-nightwatch-tests-on-a-create-react-app-on-travis

**Comment by kalote** [comment]
I just read this full issue that looked like a story ... and that was a super funny one!

Nice job!
