### ISSUE TITLE
How to run Chrome headless?

### ISSUE THREAD

**Issue by lolpez** [dwyl/learn-nightwatch#90]
Following the configuration file:

`"test_settings": {

    "default": {
        "screenshots": {
            "enabled": true, // if you want to keep screenshots
            "path": SCREENSHOT_PATH, // save screenshots here
            "on_failure": true,
            "on_error": true
        },
        "globals": {
            "waitForConditionTimeout": 5000 // sometimes internet is slow so wait.
        },
        "desiredCapabilities": { // use Chrome as the default browser for tests
            "browserName": "chrome"
        }
    },
    "chrome": {
        "desiredCapabilities": {
            "browserName": "chrome",
            "javascriptEnabled": true, // turn off to test progressive enhancement
            "chromeOptions" : {
                "args": ["headless"]
            }
        }
    }
}`

Chrome window still opens. I've found the list of arguments [here](https://peter.sh/experiments/chromium-command-line-switches/) but no results.
How can I use the Chrome driver in headless mode using nightwatch for Windows 10?

**Comment by nelsonic** [comment]
@lolpez I suggest you open this question on: https://github.com/nightwatchjs/nightwatch/issues
